### ISSUE TITLE
Auto-analysis error during Variadic Function Signature Override step

### ISSUE THREAD

**Issue by TheOnlyZac** [chaoticgd/ghidra-emotionengine-reloaded#20]
An error occurred while running auto-analysis on the Sly 1 May 2002 proto. It looked like it happened after the "Variadic Function Signature Override" step began. I believe I had all the analyzer options checked except for "Condense Filler Bytes" and "Elf Scalar Operand References". Here is the stack trace:
```
Data type _reent___new has _reent within it.
java.lang.IllegalArgumentException: Data type _reent___new has _reent within it.
	at ghidra.program.database.data.StructureDB.replaceAtOffset(StructureDB.java:1561)
	at ghidra.emotionengine.symboltable.StdumpAST$InlineStructOrUnion.addField(StdumpAST.java:336)
	at ghidra.emotionengine.symboltable.StdumpAST$InlineStructOrUnion.fill(StdumpAST.java:283)
	at ghidra.emotionengine.symboltable.StabsImporter.importDataTypes(StabsImporter.java:260)
	at ghidra.emotionengine.symboltable.StabsImporter.doImport(StabsImporter.java:177)
	at ghidra.emotionengine.symboltable.StabsAnalyzer.added(StabsAnalyzer.java:84)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:688)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:788)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:667)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:632)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:336)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: ghidra.program.model.data.DataTypeDependencyException: Data type _reent___new has _reent within it.
	at ghidra.program.database.data.CompositeDB.checkAncestry(CompositeDB.java:288)
	at ghidra.program.database.data.StructureDB.replaceAtOffset(StructureDB.java:1485)
	... 15 more

STABS> Type lookup failed: FE
STABS> Type lookup failed: FE
STABS> Type lookup failed: FE
STABS> Type lookup failed: FE
STABS> Type lookup failed: ASO
STABS> Type lookup failed: rtx_def
```

## Additional details:
Plugin version: 2.1.2
Ghidra version: 10.2.3

**Comment by TheOnlyZac** [comment]
I had forgotten that @VelocityRa told me to run it with the legacy demangler so I ran it again with that checked, and it got a lot farther but still errors out. The last thing I saw it doing was the Decompiler Parameter ID step but it definitely finished that step before the error. Here's the stack trace:
```
Data type _reent___new has _reent within it.
java.lang.IllegalArgumentException: Data type _reent___new has _reent within it.
	at ghidra.program.database.data.StructureDB.replaceAtOffset(StructureDB.java:1561)
	at ghidra.emotionengine.symboltable.StdumpAST$InlineStructOrUnion.addField(StdumpAST.java:336)
	at ghidra.emotionengine.symboltable.StdumpAST$InlineStructOrUnion.fill(StdumpAST.java:283)
	at ghidra.emotionengine.symboltable.StabsImporter.importDataTypes(StabsImporter.java:260)
	at ghidra.emotionengine.symboltable.StabsImporter.doImport(StabsImporter.java:177)
	at ghidra.emotionengine.symboltable.StabsAnalyzer.added(StabsAnalyzer.java:84)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:688)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:788)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:667)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:632)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:336)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: ghidra.program.model.data.DataTypeDependencyException: Data type _reent___new has _reent within it.
	at ghidra.program.database.data.CompositeDB.checkAncestry(CompositeDB.java:288)
	at ghidra.program.database.data.StructureDB.replaceAtOffset(StructureDB.java:1485)
	... 15 more

STABS> Type lookup failed: FE
STABS> Type lookup failed: FE
STABS> Type lookup failed: FE
STABS> Type lookup failed: FE
STABS> Type lookup failed: ASO
STABS> Type lookup failed: rtx_def
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_gc at 0011b660.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$D$g_gc at 0011b688.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_splotheapPair at 0011cd78.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$D$g_splotheapPair at 0011cda0.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$InitBei__FP3BEIP3CLQffi at 0013a460.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$StartupCatalog__Fv at 001450c8.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$StartupCm__Fv at 0014bb38.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_fontDebug at 00166798.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_gifs at 00167a10.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_dro at 001710d8.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$InitKeyhole__FP7KEYHOLE at 0018c150.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$PushMenu__FP4BLOTP2MIiiiPcii at 0019e7a8.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$D$PushMenu__FP4BLOTP2MIiiiPcii at 0019e7d0.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_mpeg at 001a1818.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$InitPo__FP2PO at 001a4be8.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$AchzFromRespk__F5RESPK at 001a6730.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_lifectr at 001c1cf8.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_asprbuf at 001d7620.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_transition at 001f9738.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$RGBA_Distortion at 001fcea8.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$U_WmFadedLevels at 0020ddf0.  Message: Expected the demangled string to contain a namespace
```
