### ISSUE TITLE
v2.1.3 error during auto-analysis

### ISSUE THREAD

**Issue by TheOnlyZac** [chaoticgd/ghidra-emotionengine-reloaded#22]
Tried to analyze the Sly 1 May proto on the newest version and got the following error.
```
STABS> Type lookup failed: FE
STABS> Type lookup failed: FE
STABS> Type lookup failed: FE
STABS> Type lookup failed: FE
STABS> Type lookup failed: ASO
STABS> Type lookup failed: rtx_def
A symbol named _start already exists at this address!
ghidra.util.exception.DuplicateNameException: A symbol named _start already exists at this address!
	at ghidra.program.database.symbol.SymbolManager.checkDuplicateSymbolName(SymbolManager.java:469)
	at ghidra.program.database.symbol.SymbolDB.doSetNameAndNamespace(SymbolDB.java:611)
	at ghidra.program.database.symbol.SymbolDB.setNameAndNamespace(SymbolDB.java:674)
	at ghidra.program.database.symbol.FunctionSymbol.setNameAndNamespace(FunctionSymbol.java:83)
	at ghidra.program.database.symbol.SymbolDB.setName(SymbolDB.java:538)
	at ghidra.program.database.function.FunctionDB.setName(FunctionDB.java:261)
	at ghidra.emotionengine.symboltable.StabsImporter.setFunctionName(StabsImporter.java:350)
	at ghidra.emotionengine.symboltable.StabsImporter.importFunctions(StabsImporter.java:287)
	at ghidra.emotionengine.symboltable.StabsImporter.doImport(StabsImporter.java:181)
	at ghidra.emotionengine.symboltable.StabsAnalyzer.added(StabsAnalyzer.java:84)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:688)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:788)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:667)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:632)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:336)
	at java.base/java.lang.Thread.run(Thread.java:1589)

Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_gc at 0011b660.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$D$g_gc at 0011b688.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_splotheapPair at 0011cd78.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$D$g_splotheapPair at 0011cda0.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$InitBei__FP3BEIP3CLQffi at 0013a460.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$StartupCatalog__Fv at 001450c8.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$StartupCm__Fv at 0014bb38.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_fontDebug at 00166798.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_gifs at 00167a10.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_dro at 001710d8.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$InitKeyhole__FP7KEYHOLE at 0018c150.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$PushMenu__FP4BLOTP2MIiiiPcii at 0019e7a8.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$D$PushMenu__FP4BLOTP2MIiiiPcii at 0019e7d0.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_mpeg at 001a1818.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$InitPo__FP2PO at 001a4be8.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$AchzFromRespk__F5RESPK at 001a6730.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_lifectr at 001c1cf8.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_asprbuf at 001d7620.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$g_transition at 001f9738.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$RGBA_Distortion at 001fcea8.  Message: Expected the demangled string to contain a namespace
Demangler GNU> Unable to demangle symbol: _GLOBAL_$I$U_WmFadedLevels at 0020ddf0.  Message: Expected the demangled string to contain a namespace
```

**Comment by chaoticgd** [comment]
Should be fixed now.
